# Generated by Django 6.0 on 2026-02-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_favorite_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='unit_type',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pcs', 'Pieces')], default='g', max_length=5),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='weight_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_at_purchase',
            field=models.CharField(default='0g', max_length=20),
        ),
    ]
