# Generated by Django 6.0 on 2026-02-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_favorite_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='reference_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin-set market reference price shown in catalog', max_digits=10, null=True),
        ),
    ]
