# Generated by Django 6.0 on 2026-03-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_shop_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Pickup')], default='DELIVERY', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_slot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
